#!/bin/sh

# This is my common way of building, but you can build however you like.
# Note if you using a proxy, you need to have it running first.

# DOCKER_BUILDKIT=1 BUILDKIT_PROGRESS=plain \
  docker build --progress=plain \
  -t evanscho/diffusers-api-3 \
  # -t evanscho/diffusers-api-3:test \
  "$@" .
